theme: jekyll-theme-dinky
title: ROS World 2020 Recap for LT and Sponsor Videos by Japanese
description: ROS World 2020でのLightning Talks and Sponsor Videosの要約（on <a href="https://rosjp.connpass.com/event/196043/" target="_blank">rosjp \#40</a>）
